### ISSUE TITLE
[QUESTION] Is there a way to max out my karma manually without using this mod?

### ISSUE THREAD

**Issue by idgas01** [RaiderKnight/RK-God-Mod#1]
I'm new to the game and I ended up with a STD.  I had to use up all my karma points to heal myself.  And I'm looking for a way to cheat and max out the karma again.  Someone recommended this mod, but I don't really want to install extra things if I don't have to.  I mean for stuff like money, I can manually give myself more money by editing my stats from within the game.  But I don't know how to edit my karma.  Could you help me out please?

**Comment by RaiderKnight** [comment]
I don't think so!
Enable the mod, do your cheat, then after disable the mod.

**Comment by RaiderKnight** [comment]
Forget to say, with this mod, you're not god... It's a mod for cheating.... so you choose what you want to higher or reduce.

**Comment by idgas01** [comment]
Found it.  But thank you for the information about the mod.  I may eventually try it one day.

LifePlay\Content\Modules\vin_Base\Stats\Longterm\karma.lpstat
